remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: [AutoFrameCAD]
description:
  [
    A BricsCAD plug-in which includes GUI for creating basic objects (e.g. walls),
  ]
show_downloads: true
