name: Illyrian's CI/CD
run-name: "Illyrian's CI/CD"

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    if: contains(github.event.head_commit.message, '.deploy')
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: setup_python
        name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: pip install -e .

      - id: create_build_dir
        name: Create Build Directory
        run: mkdir -p dardania/build

      - id: compile_to_shared_library
        name: Compile to Shared Library
        run: g++ -shared -fPIC -g dardania/test.cpp -o dardania/build/test.so

      - id: run_tests
        name: Run Tests
        run: python -m unittest discover

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: setup_python
        name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
          cache: "pip"

      - id: install_dependencies
        name: Install Dependencies
        run: pip install -e .

      - id: build_package
        name: Build Package
        run: python -m build

      - id: get_version
        name: Get Version
        run: echo VERSION=$(python setup.py --version) >> $GITHUB_OUTPUT

      - id: create_release
        name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ contains(github.event.head_commit.message, '.draft') }}
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, '.pre') }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
